title:              "Athena SG Han"
tagline:            "디지털 마케팅 블로그"
email:              "athena.sg.han@gmail.com"
description:        "디지털 마케팅, 클라우드, Digital Marketing, SEO, Technical, Contents 관련 블로그"
author:             "Athena Sul Gi Han"
baseurl:            "/"
url:                " https://athenasghan.github.io"
locale:             "ko_KR"
thumbnail:          "/img/ah.blog.thumbnail_h628.jpg"


# Social Profiles
twitter_username:   twitter_username
instagram_username: instagram_username
facebook_username:  facebook_username
linkedin_username:  linkedin_username

# Build settings
markdown:           kramdown
permalink:          /:title
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-paginate
